Laravel/spacebook/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('user/logout', ['as' => 'user.logout', 'uses' => 'UserController@logout']);
Route::get('/user/{user}/deleteFriend', ['as' => 'user.deleteFriend', 'uses' => 'UserController@deleteFriend']);
Route::get('/user/{user}/addFriend', ['as' => 'user.addFriend', 'uses' => 'UserController@addFriend']);
Route::get('/', ['as' => 'user.feed', 'uses' => 'UserController@feed']);
Route::get('user/{user}/friends', ['as' => 'user.friends', 'uses' => 'UserController@friends']);
Route::post('user/login', ['as' => 'user.login', 'uses' => 'UserController@login']);
Route::resource('post', 'PostController');
Route::resource('user', 'UserController');
Route::resource('comment', 'CommentController');

?>

Laravel/spacebook/app/models/Post.php
<?php
class Post extends Eloquent {
 	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'posts';

   public static $rules = [];
}
?>

Laravel/spacebook/app/controllers/PostController.php
<?php

class PostController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return Redirect::to('/');
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('post.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store() {
		$post = new Post;
		$input = Input::all();
		$validator = Validator::make($input, Post::$rules);
		if ($validator->passes()) {
			$post->user_id = $input['user_id'];
			$post->title = $input['title'];
			$post->text = $input['text'];
			$post->privacy = $input['privacy'];
			$post->save();
  	 	} 
  		return Redirect::to('/');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$post = Post::find($id);
		$comments = Comment::where('post_id', '=', $id)->get();
		if (!Auth::check()) return View::make('public.post.show', compact('post'), compact('comments'));
		else if ($post->privacy < 2 and Auth::check()) return View::make('post.show', compact('post'), compact('comments'));
		else if ($post->privacy == 2 and Auth::id() ==  $post->user_id) return View::make('post.show', compact('post'), compact('comments'));
		else return Redirect::to('/');
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		if (!Auth::check()) return Redirect::to('/');
		$post = Post::find($id);
		return View::make('post.edit', compact('post'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$post = Post::find($id);
		if (Auth::id() == $post->user_id) {
			$input = Input::all();
			$validator = Validator::make($input, Post::$rules);
			if ($validator->passes()) {
				$post->user_id = $input['user_id'];
				$post->title = $input['title'];
				$post->text = $input['text'];
				$post->privacy = $input['privacy'];
				$post->save();
  	 		} 
  			return Redirect::route('post.show', compact('post'));
		}
		return Redirect::to('/');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id) {
		$post = Post::find($id);
		if (Auth::id() != $post->user_id) return Redirect::to('/');
		$post -> delete();
		return Redirect::to('/');
	}


}

Laravel/spacebook/app/views/post/create.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')
  {{ Form::open(['action' => 'PostController@store']) }}
    {{ Form::hidden('user_id', Auth::id()) }}
    {{ Form::label('title', 'title') }}
    {{ Form::text('title') }}
    {{$errors->first('title')}}
    <br>
    {{ Form::label('text', 'text') }}
    {{ Form::text('text') }}
    {{$errors->first('text')}}
    <br>
    {{ Form::label('privacy', 'privacy') }}
    {{ Form::text('privacy') }}
    {{$errors->first('privacy')}}
    <br>
    {{ Form::submit('Create Post', ['class' => 'btn btn-default']) }}
  {{ Form::close() }}
@stop

Laravel/spacebook/app/views/post/edit.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')

    {{ Form::model($post, ['method' => 'PATCH', 'route' => ['post.update', $post -> id]]) }}    
        <h1>Update post</h1>
    	{{ Form::hidden('user_id', Auth::id()) }}
        {{  Form::label('title', 'title')  }}
        {{  Form::text('title')  }}
        {{  $errors->first('title')  }}
        <br>{{ Form::label('text', 'text')  }}
        {{ Form::text('text')  }}
        {{ $errors->first('text')  }}
        <br>
	{{  Form::label('privacy', 'privacy')  }}
        {{  Form::text('privacy')  }}
        {{  $errors->first('privacy')  }}
        <br>
        {{  Form::submit('Update Post', ['class' => 'btn btn-default'])  }}
    {{  Form::close()  }}
    {{  Form::model($post, ['method' => 'DELETE', 'route' => ['post.destroy', $post->id]])  }}     
        {{  Form::submit('Delete', ['class' => 'btn btn-default'])  }} 
    {{  Form::close()  }}

@stop 

Laravel/spacebook/app/views/post/show.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')
<h1>Post:</h1>
  <p>User: {{{ $post -> user_id }}}</p>
  <p>Title: {{{ $post -> title }}}</p>
  <p>Text: {{{ $post -> text }}}</p>
  {{ link_to_route('post.edit', 'Edit Post', $post->id) }}
  {{ Form::model($post, ['method' => 'DELETE', 'route' => ['post.destroy', $post['id']]]) }}     
    {{ Form::submit('Delete', ['class' => 'btn btn-default']) }} 
  {{ Form::close() }}
    
  {{ Form::open(['action' => 'CommentController@store']) }}
    {{ Form::hidden('user_id', Auth::id()) }}
    {{ Form::hidden('post_id', $post->id) }}
    {{ Form::label('message', 'message') }}
    {{ Form::text('message') }}
    {{ Form::submit('Create Comment', ['class' => 'btn btn-default']) }}
  {{ Form::close() }}
<br>
@foreach($comments as $comment)
  <p>User: {{{ $comment -> user_id }}}</p>
  <p>Message: {{{ $comment -> message }}}</p>
  {{ Form::model($comment, ['method' => 'DELETE', 'route' => ['comment.destroy', $comment['id']]]) }}     
    {{ Form::submit('Delete', ['class' => 'btn btn-default']) }} 
  {{ Form::close() }}
  {{ link_to_route('comment.edit', 'Edit comment', $comment->id) }}
@endforeach

@stop