Laravel/spacebook/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('user/logout', ['as' => 'user.logout', 'uses' => 'UserController@logout']);
Route::get('/user/{user}/deleteFriend', ['as' => 'user.deleteFriend', 'uses' => 'UserController@deleteFriend']);
Route::get('/user/{user}/addFriend', ['as' => 'user.addFriend', 'uses' => 'UserController@addFriend']);
Route::get('/', ['as' => 'user.feed', 'uses' => 'UserController@feed']);
Route::get('user/{user}/friends', ['as' => 'user.friends', 'uses' => 'UserController@friends']);
Route::post('user/login', ['as' => 'user.login', 'uses' => 'UserController@login']);
Route::resource('post', 'PostController');
Route::resource('user', 'UserController');
Route::resource('comment', 'CommentController');

?>

Laravel/spacebook/app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {


	public static $rules = ['email' => 'required|unique:users|min:4', 'password' => 'required|min:8'];
	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

}

Laravel/spacebook/app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Lists all profiles
	 *
	 * @return Response
	 */
	 

	public function index() {
		$users = User::all();
		return View::make('user.index', compact('users'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create() {
		return View::make('user.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store() {
		$user = new User;
		$input = Input::all();
		$password = $input['password'];
		$encrypted = Hash::make($password);
		$validator = Validator::make($input, User::$rules);
		if ($validator->passes()) {
			$user->email = $input['email'];
			$user->name = $input['name'];
			$user->dob = $input['dob'];
			$user->password = $encrypted;
			$user->save();
  			return Redirect::action('user.show', array($user->id));
  	 	} else {
			return Redirect::action('user.create')->withErrors($validator);
		}
	}	


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id) {
		$user = User::find($id);
		$authposts = Post::where('user_id', '=', $id)->where('privacy', '=', 0)->get();
		$friends = Friend::all();
		if (Auth::id() == $id) {
			$authposts = $authposts->merge(Post::where('user_id', '=', $id)->where('privacy', '=', 2)->get());
		}
		if (Auth::check()) {
			$authposts = $authposts->merge(Post::where('user_id', '=', $id)->where('privacy', '=', 1)->get());
			foreach ($friends as $friend) {
				if (($friend->user_id == $user->email and $friend->friend_id == Auth::user()->email) or ($friend->friend_id == $user->email and $friend->user_id == Auth::user()->email)) {
					return View::make('user.showDelete', compact('user'), compact('authposts')); 
				}
			}
			return View::make('user.showAdd', compact('user'), compact('authposts')); 
		}
		return View::make('public.user.show', compact('user'), compact('authposts'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @return Response
	 */
	public function edit() {
		if (!Auth::check()) return Redirect::to('/');
		$user = Auth::user();
		return View::make('user.edit', compact('user')); 
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)	{
		if (Auth::id() !=  $id) return Redirect::route('public.user.feed');
		$user = User::find($id);
		$input = Input::all();
		$password = $input['password'];
		$encrypted = Hash::make($password);
		$validator = Validator::make($input, User::$rules);
		if ($validator->passes()) {
			$user->username = $input['username'];
			$user->password = $encrypted;
			$user->save();
  			return Redirect::action('user.show', array($user->id));
  	 	} else {
			return Redirect::action('user.edit', array($user->id))->withErrors($validator);
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id) {	
		$user = User::find($id);
		if (Auth::id() != $user->id) return Redirect::to('/');
		$user -> delete();
		return Redirect::to('user');
	}
	
	public function login() {
		$userdata = ['email' => Input::get('email'), 'password' => Input::get('password')];
		if (Auth::attempt($userdata)) {
			return Redirect::to(URL::previous());
		} else {
			Session::put('login_error', 'Login Failed: Username or password incorrect');
			return Redirect::to(URL::previous())->withInput();
		}
	}
	
	public function friends($id) {
		$user = User::find($id);
		$users = new \Illuminate\Database\Eloquent\Collection;
		foreach (Friend::all() as $friend) {
			if ($friend->user_id == $user->email) {
				$users = $users->merge(User::where('email', '=', $friend->friend_id)->get());
			} else if ($friend->friend_id == $user->email) {
				$users = $users->merge(User::where('email', '=', $friend->user_id)->get());
			}
		}
		return View::make('user.friends', compact('users'));
	}

	public function addFriend($id) {
		$user = User::find($id);
		$friend = new Friend;
		$friend->user_id = Auth::user()->email;
		$friend->friend_id = $user->email;
		$friend->save();
		return Redirect::to(URL::previous());
	}

	public function deleteFriend($id) {
		$user = User::find($id);
		Friend::where('user_id', '=', $user->email)->where('friend_id', '=', Auth::user()->email)->delete();
		Friend::where('user_id', '=', Auth::user()->email)->where('friend_id', '=', $user->email)->delete();
		return Redirect::back();
	}

	public function feed() {
		$posts = Post::all();
		if (!Auth::check()) {
			$authposts = [];
			foreach ($posts as $post) {
				if ($post->privacy == 0) {
					$authposts[] = $post;
				}
			}
			return View::make('public.user.feed', compact('authposts'));
		} else {
			$authposts = [];
			foreach ($posts as $post) {
				if ($post->privacy == 0) {
					$authposts[] = $post;
				} else if ($post->privacy == 1) {
					$authposts[] = $post;
				} else if ($post->privacy == 2 and Auth::id() == $post->user_id) {
					$authposts[] = $post;
				}
			}
			return View::make('user.feed', compact('authposts'));
		}
	}	

	public function logout() {
		Auth::logout();
		return Redirect::to('/');
	}

	public function settings($id) {
		if (!Auth::check()) return Redirect::route('public.user.feed');
		$user = User::find($id);
		return View::make('user.settings', compact('user')); 
	}
}

Laravel/spacebook/app/views/user/create.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')

    {{ Form::open(['action' => 'UserController@store']) }}
        <h1>Create New User:</h1>
        {{ Form::label('email', 'Email') }}
        {{ Form::text('email') }}
        {{$errors->first('email')}}
        <br>
	{{ Form::label('name', 'Name') }}
        {{ Form::text('name') }}
        {{$errors->first('name')}}
        <br>
	{{ Form::label('dob', 'Dob') }}
        {{ Form::text('dob') }}
        {{$errors->first('dob')}}
        <br>
        {{ Form::label('price', 'Password') }}
        {{ Form::password('password') }}      
        {{$errors->first('password')}}
        <br>
        {{ Form::submit('Create User', ['class' => 'btn btn-default']) }}
    {{ Form::close() }}

@stop

Laravel/spacebook/app/views/user/edit.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')

    {{ Form::model($user, ['method' => 'PATCH', 'route' => ['user.update', $user -> id]]) }}    
        {{ Form::label('email', 'Email') }}
        {{ Form::text('email') }}
        {{$errors->first('email')}}
        <br>
	{{ Form::label('name', 'Name') }}
        {{ Form::text('name') }}
        {{$errors->first('name')}}
        <br>
	{{ Form::label('dob', 'Dob') }}
        {{ Form::text('dob') }}
        {{$errors->first('dob')}}
        <br>
        {{ Form::label('price', 'Password') }}
        {{ Form::password('password') }}      
        {{$errors->first('password')}}
        <br>
        {{ Form::submit('Update Product', ['class' => 'btn btn-default']) }}
    {{ Form::close() }}

    {{ Form::model($user, ['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) }}     
        {{ Form::submit('Delete', ['class' => 'btn btn-default']) }} 
    {{ Form::close() }}

@stop 

Laravel/spacebook/app/views/user/feed.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')
<a href="{{{ url('user') }}}">Add Friends</a>
  <h1>Make A Post:</h1>
  {{ Form::open(['action' => 'PostController@store']) }}
    {{ Form::hidden('user_id', Auth::id()) }}
    {{ Form::label('title', 'title') }}
    {{ Form::text('title') }}
    {{$errors->first('title')}}
    <br>
  {{ Form::label('text', 'text') }}
    {{ Form::text('text') }}
    {{$errors->first('text')}}
    <br>
  {{ Form::label('privacy', 'privacy') }}
    {{ Form::text('privacy') }}
    {{$errors->first('privacy')}}
    <br>
    {{ Form::submit('Create Post', ['class' => 'btn btn-default']) }}
  {{ Form::close() }}
<h1>All Posts:</h1>
@foreach($authposts as $post)
    <p>User: {{{ $post -> user_id }}}</p>
    <p>Title: {{{ $post -> title }}}</p>
    <p>Text: {{{ $post -> text }}}</p>
    <p>Privacy: {{{ $post -> privacy }}}</p>
    {{ link_to_route('post.show', 'View post', $post -> id)  }}
    <br>
@endforeach
@stop

Laravel/spacebook/app/views/user/friends.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')
<h1>All Friends:</h1>
@foreach($users as $user)
    <p>Email: {{{ $user->email }}}</p>
    {{ link_to_route('user.show', 'View Profile', $user['id'])  }}
    <br>
@endforeach
@stop

Laravel/spacebook/app/views/user/index.blade.php
@extends('layouts.master')

@section('title')
    Lab 10
@stop

@section('column2')

<h1>All Users:</h1>
@foreach($users as $user)
    <p>Email: {{{ $user -> email }}}</p>
    {{ link_to_route('user.show', 'View User', $user -> id)  }}
@endforeach

@stop

Laravel/spacebook/app/views/user/showAdd.blade.php
@extends('layouts.master')

@section('title')
    Profile
@stop

@section('column2')
        <p>Name: {{{ $user->name }}}</p>
        <p>Email: {{{ $user->email }}}</p>
        <p>Date of Birth: {{{ $user->dob }}}</p>
    {{ link_to_route('user.addFriend', 'Add Friend', $user->id) }}
    <br>
    {{  link_to_route('user.index', 'Back to All Users')  }}  
    {{  link_to_route('user.friends', 'Show Friends', $user['id'])  }} 
@foreach($authposts as $post)
    <p>User: {{{ $post -> user_id }}}</p>
    <p>Title: {{{ $post -> title }}}</p>
    <p>Text: {{{ $post -> text }}}</p>
    <p>Privacy: {{{ $post -> privacy }}}</p>
    {{ link_to_route('post.show', 'View post', $post -> id)  }}
    <br>
@endforeach

@stop

Laravel/spacebook/app/views/user/showDelete.blade.php
@extends('layouts.master')

@section('title')
    Profile
@stop

@section('column2')
    <p>Name: {{{ $user->name }}}</p>
    <p>Email: {{{ $user->email }}}</p>
    <p>Date of Birth: {{{ $user->dob }}}</p>
    {{ link_to_route('user.deleteFriend', 'Delete Friend', $user->id) }}
    <br>
    {{  link_to_route('user.index', 'Back to All Users')  }}  
    {{  link_to_route('user.friends', 'Show Friends', $user['id'])  }} 
@foreach($authposts as $post)
    <p>User: {{{ $post -> user_id }}}</p>
    <p>Title: {{{ $post -> title }}}</p>
    <p>Text: {{{ $post -> text }}}</p>
    <p>Privacy: {{{ $post -> privacy }}}</p>
    {{ link_to_route('post.show', 'View post', $post -> id)  }}
    <br>
@endforeach

@stop

Laravel/spacebook/app/views/user/signin.blade.php
{{--This is the layout for the login page--}}

@extends('layouts.master')

@section('column2')
<div class="panel panel-default">
    <div class ="panel-body">
    <div class="account-wall">
      <h1 class="text-center login-title">Sign in to Spacebook</h1>
      <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" alt="">
      <form class="form-signin">
      <input type="text" class="form-control" placeholder="Email" required autofocus>
      <input type="password" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <label class="checkbox pull-left">
        <input type="checkbox" value="remember-me">Remember me
      </label>
      <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
      </form>
      <a href="#" class="text-center new-account">Create an account </a>
    </div>
  </div>
</div>
@stop